// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyvirooiwzqckbxfukvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dmlyb29pd3pxY2tieGZ1a3ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTE3MjcsImV4cCI6MjA2ODY2NzcyN30.5VXA1WoSgsu9ykNuVFGjFclv4gKdWV5kUH2G5fvBTRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});